### PR TITLE
removed Oracle JDK from CI build and added OpenJDK 11

### PR DESCRIPTION
**Pull request by slu-it**

### CODE REVIEW

**Comment by slu-it** [comment]
@antoniq I'll have to take a look at why the tests are failing under JDK 11 .. will update this later

**Comment by slu-it** [comment]
@antoniq I tried to fix all JDK 11 related issues by mostly updating the dependencies. For some reason this only solved the issues for the enrichment service.

The underlying problem is the continued use of `Unsafe` by the current version of Mockito for Kotlin and even Mockk.

One of us should look at this in the future... for now I disabled JDK 11 build for the Slack integration service.

**Comment by antoniq** [comment]
@slu-it  I have created an issue for the problem for easier tracking: https://github.com/nt-ca-aqe/library-app/issues/26
For the library-service the contract tests are currently failing, we should have a look at that as well.

**Comment by slu-it** [comment]
hm... "it ran on my machine" :D 

I'll check that out tomorrow...

**Pull request closed without merging**
